experiment_name: "mqt_brisbane"

hardware: 
  - kind: "ibm"
    id: "brisbane"

layouts: ["trivial"]
k: [2, 3, 8, 13, 26, 127] #"balanced"
layout_seed: "fix"

source: "mqt"
circuits:
  bench_num_qubits: "max"
  names: []
  num_transpiler_seeds: 20


qpg_low_limit: 1
virtual_rz: true
optimization_level: 1

generic_gate_durations: 
  single_qubit_gate: [20e-9]
  two_qubit_gate: [200e-9]
  switch_gate: [02e-9]

topord_method: ["prio_two"]
