experiment_name: "grids_random"

hardware: 

  - kind: "chalmers_grid"
    id: "5x5"
  - kind: "chalmers_grid"
    id: "11x11"

layouts: ["trivial"]
k: [2] #"balanced"
layout_seed: "fix"

source: "random"
circuits:
  num_circuits: 10
  num_gates: [100, 250, 500]

needs_translation: false
needs_routing: true

qpg_low_limit: 1
virtual_rz: true
optimization_level: 1

generic_gate_durations: 
  single_qubit_gate: [20e-9]
  two_qubit_gate: [200e-9]
  switch_gate: [02e-9]

topord_method: ["prio_two"]
